Algoritmo "Media Idade"

Var
  nome1,nome2 : caractere
  idade1,idade2 : inteiro
  media : real

Inicio

     escreval ("Dados da primeira pessoa")
     escreva("Nome: ")
     leia(nome1)
     escreva("Idade: ")
     leia(idade1)
     escreval ("Dados da segunda pessoa")
     escreva("Nome: ")
     leia(nome2)
     escreva("Idade: ")
     leia(idade2)
     media <- (idade1+idade2)/2.00
     escreva("A média de idade da ",nome1," com o ",nome2," é de: ",media:3:1)
   


Fimalgoritmo